### ISSUE TITLE
Second RDS の内容を main RDS の Database に Readonly でレプリケートする

### ISSUE THREAD

**Issue by takyafumin** [takyafumin/sample-rds-replication#2]
Second RDS の内容を main RDS の Database に Readonly でレプリケートする。

- main RDS
  - hogedb
  - fugadb   <== replicate == fugadb(Second RDS)

**Comment by takyafumin** [comment]
# 指示プロンプト

---

既存の Aurora MySQL 環境（rds-replication.yaml で構築）に対して、AWS DMS レプリケーションを追加するための新しい CloudFormation テンプレートを作成してください。この新しいテンプレートは、既存のスタックの出力値を参照して DMS リソースを構成します。

## 要件
1. 新しい CloudFormation テンプレート（dms-replication.yaml）を作成
2. 既存のスタックの出力値を参照パラメータとして使用
3. セカンドDB上の world データベースからマスターDBへのリードオンリーレプリケーションを設定
4. employees データベースはレプリケーション対象外とする

## テンプレートの構成

### パラメータセクション
```yaml
Parameters:
  # 既存スタックの名前
  ExistingStackName:
    Type: String
    Description: 既存の Aurora MySQL スタックの名前
    
  # データベース認証情報
  DBUsername:
    Type: String
    Description: データベースユーザー名
    
  DBPassword:
    Type: String
    NoEcho: true
    Description: データベースパスワード
    
  # DMS インスタンスの設定
  DMSInstanceClass:
    Type: String
    Default: dms.t3.medium
    Description: DMS レプリケーションインスタンスのクラス
    
  # レプリケーション対象データベース
  SourceDatabaseName:
    Type: String
    Default: world
    Description: レプリケーション対象のデータベース名
```

### リソースセクション
以下のリソースを含めてください：

1. **DMS サブネットグループ**
   - 既存の VPC のプライベートサブネットを使用

2. **DMS 用セキュリティグループ**
   - 既存の RDS セキュリティグループとの通信を許可

3. **DMS サービスロール**
   - 必要な IAM ロールとポリシー

4. **DMS レプリケーションインスタンス**
   - 指定されたインスタンスクラスを使用
   - マルチ AZ は false（テスト環境のため）

5. **DMS ソースエンドポイント**
   - タイプ: ソース
   - エンジン: aurora
   - サーバー名: 既存スタックの SecondDBEndpoint 出力値を参照
   - データベース名: world（パラメータから）
   - 追加接続属性: binlogRowImage=full

6. **DMS ターゲットエンドポイント**
   - タイプ: ターゲット
   - エンジン: aurora
   - サーバー名: 既存スタックの MasterDBEndpoint 出力値を参照
   - データベース名: world（パラメータから）

7. **DMS レプリケーションタスク**
   - 移行タイプ: 全ロードおよび継続的な変更のキャプチャ
   - ターゲットテーブル準備モード: 切り捨て
   - テーブルマッピング: world スキーマのみをレプリケート、employees スキーマを除外

### 出力セクション
```yaml
Outputs:
  DMSTaskARN:
    Description: DMS レプリケーションタスクの ARN
    Value: !Ref DMSReplicationTask
    
  StopTaskCommand:
    Description: レプリケーションタスクを停止するコマンド
    Value: !Sub "aws dms stop-replication-task --replication-task-arn ${DMSReplicationTask}"
    
  StartTaskCommand:
    Description: レプリケーションタスクを再開するコマンド
    Value: !Sub "aws dms start-replication-task --replication-task-arn ${DMSReplicationTask} --start-replication-task-type resume-processing"
```

## 重要な考慮事項

1. **既存スタックの参照方法**
   - Fn::ImportValue を使用して既存スタックの出力値を参照
   - または、パラメータとして既存スタックの名前を受け取り、Fn::GetAtt で値を取得

2. **テーブルマッピングの JSON 設定**
   - world スキーマのみを含め、employees スキーマを除外する設定
   - 必要に応じて特定のテーブルのみを選択可能に

3. **Aurora パラメータグループの設定**
   - 既存の Aurora クラスターでバイナリログが有効になっていることを前提とする
   - または、このテンプレートで新しいパラメータグループを作成し、既存クラスターに適用する方法も提示

4. **デプロイ手順**
   - 新しいテンプレートのデプロイ前に必要な準備手順
   - サンプルデータベースのインポート方法
   - マスターDB側に空の world データベースを作成する方法

## 追加のヘルパースクリプト
EC2 踏み台サーバーで使用するヘルパースクリプトも含めてください：

1. サンプルデータベースのインポートスクリプト
2. レプリケーション検証用のスクリプト
3. DMS タスク管理（停止・開始）スクリプト

これらのスクリプトは、新しいスタックのデプロイ後に EC2 踏み台サーバーにコピーして使用する手順も含めてください。
